apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-counts
spec:
  hard:
    pods: "2"
    configmaps: "2"
    persistentvolumeclaims: "4"
    replicationcontrollers: "4"
    secrets: "10"
    services: "10"
