---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2

params:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:
  NETWORK_NAME:
  SCS_SINGLETON_JOB_AZ:
  DEPLOYMENT_NW_AZS:
  PRODUCT_NAME:

inputs:
  - name: nsx-t-ci-pipeline

run:
  path: nsx-t-ci-pipeline/tasks/config-scs/task.sh
