---

platform: linux

image_resource:
  type: docker-image
  source: {repository: czero/cflinuxfs2}

params:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:
  VCENTER_HOST:
  VCENTER_USR:
  VCENTER_PWD:
  VCENTER_DATA_CENTER:
  VCENTER_DISK_TYPE:
  EPHEMERAL_STORAGE_NAMES:
  PERSISTENT_STORAGE_NAMES:
  BOSH_VM_FOLDER:
  BOSH_TEMPLATE_FOLDER:
  BOSH_DISK_PATH:
  ICMP_CHECKS_ENABLED:
  INFRA_NETWORK_NAME:
  INFRA_VCENTER_NETWORK:
  INFRA_NW_CIDR:
  INFRA_EXCLUDED_RANGE:
  INFRA_NW_DNS:
  INFRA_NW_GATEWAY:
  INFRA_NW_AZS:
  DEPLOYMENT_NETWORK_NAME:
  DEPLOYMENT_VCENTER_NETWORK:
  DEPLOYMENT_NW_CIDR:
  DEPLOYMENT_EXCLUDED_RANGE:
  DEPLOYMENT_NW_DNS:
  DEPLOYMENT_NW_GATEWAY:
  DEPLOYMENT_NW_AZS:
  AZ_1:
  AZ_1_CLUSTER_NAME:
  AZ_1_RP_NAME:
  AZ_2:
  AZ_2_CLUSTER_NAME:
  AZ_2_RP_NAME:
  AZ_3:
  AZ_3_CLUSTER_NAME:
  AZ_3_RP_NAME:
  NTP_SERVERS:
  OPS_DIR_HOSTNAME:
  ENABLE_VM_RESURRECTOR:
  MAX_THREADS:
  TRUSTED_CERTIFICATES:
  NSX_NETWORKING_ENABLED:
  NSX_ADDRESS:
  NSX_USERNAME:
  NSX_PASSWORD:
  NSX_CA_CERTIFICATE:
  NSX_MODE:
  
  
inputs:
  - name: nsx-t-ci-pipeline

run:
  path: nsx-t-ci-pipeline/tasks/config-opsdir-2.0-nsx-t-poc/task.sh
