---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2

params:
  NSX_API_MANAGER:
  NSX_API_USER:
  NSX_API_PASSWORD:
  PKS_SYSTEM_DOMAIN:
  VALIDATE_FOR_PAS:
  PKS_T0_ROUTER_NAME:
  PKS_CONTAINER_IP_BLOCK_NAME:
  PKS_NODES_IP_BLOCK_NAME:
  PKS_EXTERNAL_IP_POOL_NAME:
  PKS_VCENTER_CLUSTER_LIST:

inputs:
  - name: nsx-t-ci-pipeline

run:
  path: nsx-t-ci-pipeline/tasks/validate-nsx-t-for-pks/task.sh
