---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2

params:
  IAAS:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:
  PKS_SINGLETON_JOB_AZ:
  PKS_NW_AZS:
  PKS_DEPLOYMENT_NETWORK_NAME:
  PKS_CLUSTER_SERVICE_NETWORK_NAME:
  PKS_SSL_CERT:
  PKS_SSL_PRIVATE_KEY:
  PKS_SYSTEM_DOMAIN:
  PKS_UAA_DOMAIN_PREFIX:
  NSX_API_MANAGER:
  NSX_API_USER:
  NSX_API_PASSWORD:
  NSX_API_CA_CERT:
  NSX_SKIP_SSL_VERIFICATION:
  NSX_API_CA_CERT:
  PKS_VCENTER_HOST:
  PKS_VCENTER_USR:
  PKS_VCENTER_PWD:
  PKS_VCENTER_DATA_CENTER:
  PKS_VCENTER_DATASTORE:
  PKS_VCENTER_CLUSTER:
  PKS_VM_FOLDER:
  PKS_CLI_USER:
  PKS_CLI_PASSWORD:
  PKS_CLI_EMAIL:
  PKS_PLAN_DETAILS:
  PKS_T0_ROUTER_ID:
  PKS_IP_BLOCK_ID:
  PKS_FLOATING_IP_POOL_IDS:
  PKS_SYSLOG_MIGRATION_ENABLED:
  PKS_SYSLOG_ADDRESS:
  PKS_SYSLOG_PORT:
  PKS_SYSLOG_TRANSPORT_PROTOCOL:
  PKS_SYSLOG_TLS_ENABLED:
  PKS_SYSLOG_PEER:
  PKS_SYSLOG_CA_CERT:


inputs:
  - name: nsx-t-ci-pipeline

run:
  path: nsx-t-ci-pipeline/tasks/config-pks/task.sh
