---
platform: linux

image_resource:
  type: docker-image
  source: {repository: czero/rootfs}

inputs:
- name: nsx-t-ci-pipeline

params:
  PRODUCT_NAME:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:
  ERRANDS_TO_RUN_ON_CHANGE:

run:
  path: nsx-t-ci-pipeline/tasks/config-errands/task.sh